In [2]:
import numpy as np

import numpy as np

# Given matrix A
A = np.array([[-0.1495, -0.1986, -0.9685],
              [-0.8256,  0.5640,  0.0117],
              [-0.5439, -0.8015,  0.2484]])

# Compute the Gram matrix (A^T A)
G = A.T @ A

# Compute identity matrix of same size
I = np.eye(A.shape[0])

# Check if G is close to identity
is_orthogonal = np.allclose(G, I)

print("Gram matrix:\n", G)
print("\nIs A orthogonal?", is_orthogonal)


Gram matrix:
 [[ 9.9979282e-01 -1.1850000e-05  2.6470000e-05]
 [-1.1850000e-05  9.9994021e-01 -1.4970000e-04]
 [ 2.6470000e-05 -1.4970000e-04  9.9983170e-01]]

Is A orthogonal? False
